### ISSUE TITLE
Is /tmp/imdb-rename an unusual default data_dir?

### ISSUE THREAD

**Issue by dnwe** [BurntSushi/imdb-rename#11]
It seems like the .tsv files from imdb should be considered as cache files, and as such would naturally go under `~/.cache` or `~/Library/Caches` or `%LOCALAPPDATA%` on Linux, Mac, Windows respectively? Either by pulling in https://docs.rs/dirs/1.0.4/dirs/fn.cache_dir.html or just rolling your own consts

**Comment by BurntSushi** [comment]
I don't feel that strongly about this in either direction. I personally think a tmp directory is just fine, but sure, using `dirs` might be a bit better here.

**Comment by kikoreis** [comment]
The thing with a tmp directory is that it gets blown away in a number of scenarios, including a simple reboot in commonly deployed operating systems, including the latest Ubuntu 20.04 LTS. And given the regeneration of the database isn't cheap, it makes sense to try and keep it around. I agree that ~/.cache makes sense for Linux.

**Comment by BurntSushi** [comment]
Of course I understand that `/tmp` gets blown away. That's why the directory is configurable.

I don't think it's worthwhile to pursue platform specific directories here, which is in and of itself a ball of mud. Allowing the user to choose, with a default to `/tmp`, seems good enough to me.
