### ISSUE TITLE
Cant build database, mem leak?

### ISSUE THREAD

**Issue by vredesbyyrd** [BurntSushi/imdb-rename#12]
Thanks for sharing this awesome tool :) 

Starting with version `0.1.2-1` the database fails to completely download and causes the system to freeze. The only way out is powering off the machine . I noticed that while downloading the db, memory jumped from 2gb to 9.8gb.   I assume that commit 09e07a22e9d8eae9b8ad79ecfe347a1d44ac2c0f is the reason? This is on a laptop with 10gigs of ram and no swap...but I am now second guessing my decision to forego a swap partition...  😿

Now that the cvs data is initially read into memory, is 8+ gb expected behavior? 

Thanks for your time. 

**env info**

Imdb-rename-0.1.2-1
rust 1:1.34.0-1
Arch linux Kernel 5.0.11-1

**Comment by BurntSushi** [comment]
Here is what happens when I try to build the database:

```
$ time imdb-rename --update-data
INFO: downloading https://datasets.imdbws.com/title.akas.tsv.gz to /tmp/imdb-rename/title.akas.tsv
INFO: downloading https://datasets.imdbws.com/title.basics.tsv.gz to /tmp/imdb-rename/title.basics.tsv
INFO: downloading https://datasets.imdbws.com/title.episode.tsv.gz to /tmp/imdb-rename/title.episode.tsv
INFO: downloading https://datasets.imdbws.com/title.ratings.tsv.gz to /tmp/imdb-rename/title.ratings.tsv
INFO: creating index at /tmp/imdb-rename/index
INFO: 3777556 alternate names indexed
INFO: created AKA index (took 1.1089 secs)
INFO: 930067 ratings indexed
INFO: created rating index (took 1.4289 secs)
INFO: 4042463 episodes indexed
INFO: created episode index (took 18.8673 secs)
INFO: 5660654 titles indexed
INFO: 7070650 total names indexed
INFO: created name index, ngram type: window, ngram size: 3 (took 21.3420 secs)

real    49.516
user    56.970
sys     6.261
maxmem  7007 MB
faults  0
```

Notably, peak memory usage jump to 7GB. So yeah, that looks like a problem. It explains your symptoms if your machine doesn't have enough memory to handle this.

This isn't a memory leak though. I'll see if there's a simple fix I can make to get this working.

**Comment by BurntSushi** [comment]
All right, I added a fix that should make memory usage go down quite a bit. We do still need to load all the data into memory and sort the records first though.

**Comment by vredesbyyrd** [comment]
Thank you for the explanation and quick fix. I just tested 2ea88a0 and building the databases required much less memory, only 1.7GB  👍 

```
        Command being timed: "imdb-rename --update-data"
	User time (seconds): 126.11
	System time (seconds): 4.64
	Percent of CPU this job got: 33%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 6:33.50
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
        **Maximum resident set size (kbytes): 1798200**    
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 560749
	Voluntary context switches: 118252
	Involuntary context switches: 19866
	Swaps: 0
	File system inputs: 0
	File system outputs: 0
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0

```
