### ISSUE TITLE
Error indexing

### ISSUE THREAD

**Issue by gd4c** [BurntSushi/imdb-rename#26]
`fst error: Error inserting out-of-order key: tt1000100. (Previous key was tt10001000.) Keys must be inserted in lexicographic order.`

using Feb 1 datasets

**Comment by BurntSushi** [comment]
Please provide a reproduction. I cannot reproduce:

```
$ imdb-rename --version
imdb-rename 0.1.6
$ imdb-rename --update-data
INFO: downloading https://datasets.imdbws.com/title.akas.tsv.gz to /home/andrew/tmp/imdb-rename-data/title.akas.tsv
INFO: sorting CSV records
INFO: downloading https://datasets.imdbws.com/title.basics.tsv.gz to /home/andrew/tmp/imdb-rename-data/title.basics.tsv
INFO: sorting CSV records
INFO: downloading https://datasets.imdbws.com/title.episode.tsv.gz to /home/andrew/tmp/imdb-rename-data/title.episode.tsv
INFO: sorting CSV records
INFO: downloading https://datasets.imdbws.com/title.ratings.tsv.gz to /home/andrew/tmp/imdb-rename-data/title.ratings.tsv
INFO: sorting CSV records
INFO: creating index at /home/andrew/tmp/imdb-rename-data/index
INFO: 1398648 ratings indexed
INFO: created rating index (took 0.9419 secs)
INFO: 7558199 alternate names indexed
INFO: created AKA index (took 1.0580 secs)
INFO: 10195485 titles indexed
INFO: 15016904 total names indexed
INFO: created name index, ngram type: window, ngram size: 3 (took 16.0140 secs)
INFO: 8050359 episodes indexed
INFO: created episode index (took 22.1158 secs)
```

I compiled from `master`.

**Comment by gd4c** [comment]
1. Download datasets manually (I did due to network issues)
2. Extract using gzip
3. Put in `folder`
4. Run `imdb-rename.exe --data-dir folder`

```
INFO: creating index at folder\index
fst error: Error inserting out-of-order key: tt1000100. (Previous key was tt10001000.) Keys must be
inserted in lexicographic order.
```

Using version 0.1.5

**Comment by BurntSushi** [comment]
> Using version 0.1.5

I don't support older versions.

Please use the latest version. Even if that means building it from source. If you still have a problem, then please provide a precise set of commands to reproduce the problem. You gave me prose.

**Comment by gd4c** [comment]
I understand. Could you make a binary release for v 0.1.6? I would be grateful.

**Comment by BurntSushi** [comment]
I have no plans to, sorry. It would easily take me a day of wrangling with CI and I don't see much of a point for a small little tool like this. It should be very easily to build it yourself. Much easier than me dealing with a CI release workflow.

**Comment by gd4c** [comment]
It is not as easy for me as you think. I am not at that level, yet. But I respect your decision.
