### ISSUE TITLE
Symlink support?

### ISSUE THREAD

**Issue by evanrichter** [BurntSushi/imdb-rename#7]
would there be interest in adding symlink support? I personally prefer this approach to library management, and have changed `std::fs::rename` to `std::os::unix::fs::symlink` for my own use. I understand symlinks would need to be implemented os-agnostic to support windows.

Let me know if you would like a PR and I can try to add windows support for symlinking and a proper cli option

**Comment by BurntSushi** [comment]
If the PR is simple and easy to maintain, then yeah, I can take it on.

To make it easier, feel free to return an error on Windows if the cli option is used. Symlinks on Windows are crazy anyway.

**Comment by evanrichter** [comment]
#9
